{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "An error occurred: Message: no such window: target window already closed\n",
      "from unknown error: web view not found\n",
      "  (Session info: chrome=132.0.6834.84)\n",
      "Stacktrace:\n",
      "\tGetHandleVerifier [0x00640A13+25091]\n",
      "\t(No symbol) [0x005CA584]\n",
      "\t(No symbol) [0x004AB3B3]\n",
      "\t(No symbol) [0x0048CEEB]\n",
      "\t(No symbol) [0x00517F4F]\n",
      "\t(No symbol) [0x0052AD69]\n",
      "\t(No symbol) [0x00511C46]\n",
      "\t(No symbol) [0x004E3175]\n",
      "\t(No symbol) [0x004E42FD]\n",
      "\tGetHandleVerifier [0x00936493+3128451]\n",
      "\tGetHandleVerifier [0x0094994B+3207483]\n",
      "\tGetHandleVerifier [0x009445F2+3186146]\n",
      "\tGetHandleVerifier [0x006D70C0+641200]\n",
      "\t(No symbol) [0x005D36BD]\n",
      "\t(No symbol) [0x005D0738]\n",
      "\t(No symbol) [0x005D08D6]\n",
      "\t(No symbol) [0x005C3040]\n",
      "\tBaseThreadInitThunk [0x75A17BA9+25]\n",
      "\tRtlInitializeExceptionChain [0x77CAC0CB+107]\n",
      "\tRtlClearBits [0x77CAC04F+191]\n",
      "\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "import time\n",
    "from typing import Optional\n",
    "import zipfile\n",
    "\n",
    "def checker(email: str, proxy: str) -> Optional[bool]:\n",
    "\n",
    "    username, password_host_port = proxy.split(':', 1)\n",
    "    password, host_port = password_host_port.split('@', 1)\n",
    "    host, port = host_port.split(':')\n",
    "\n",
    "    manifest_json = \"\"\"\n",
    "    {\n",
    "        \"version\": \"1.0.0\",\n",
    "        \"manifest_version\": 2,\n",
    "        \"name\": \"Chrome Proxy\",\n",
    "        \"permissions\": [\n",
    "            \"proxy\",\n",
    "            \"tabs\",\n",
    "            \"unlimitedStorage\",\n",
    "            \"storage\",\n",
    "            \"<all_urls>\",\n",
    "            \"webRequest\",\n",
    "            \"webRequestBlocking\"\n",
    "        ],\n",
    "        \"background\": {\n",
    "            \"scripts\": [\"background.js\"]\n",
    "        },\n",
    "        \"minimum_chrome_version\":\"22.0.0\"\n",
    "    }\n",
    "    \"\"\"\n",
    "\n",
    "    background_js = \"\"\"\n",
    "    var config = {\n",
    "            mode: \"fixed_servers\",\n",
    "            rules: {\n",
    "            singleProxy: {\n",
    "                scheme: \"http\",\n",
    "                host: \"%s\",\n",
    "                port: parseInt(%s)\n",
    "            },\n",
    "            bypassList: [\"localhost\"]\n",
    "            }\n",
    "        };\n",
    "\n",
    "    chrome.proxy.settings.set({value: config, scope: \"regular\"}, function() {});\n",
    "\n",
    "    function callbackFn(details) {\n",
    "        return {\n",
    "            authCredentials: {\n",
    "                username: \"%s\",\n",
    "                password: \"%s\"\n",
    "            }\n",
    "        };\n",
    "    }\n",
    "\n",
    "    chrome.webRequest.onAuthRequired.addListener(\n",
    "                callbackFn,\n",
    "                {urls: [\"<all_urls>\"]},\n",
    "                ['blocking']\n",
    "    );\n",
    "    \"\"\" % ((host, port, username, password))\n",
    "\n",
    "\n",
    "\n",
    "    try:\n",
    "        # Создание экземпляра веб-драйвера с заданными опциями\n",
    "        chrome_options = webdriver.ChromeOptions()\n",
    "\n",
    "        pluginfile = 'proxy_auth_plugin.zip'\n",
    "\n",
    "        with zipfile.ZipFile(pluginfile, 'w') as zp:\n",
    "            zp.writestr(\"manifest.json\", manifest_json)\n",
    "            zp.writestr(\"background.js\", background_js)\n",
    "\n",
    "        chrome_options.add_extension(pluginfile)\n",
    "\n",
    "        service = Service('....') #path to chrome_driver.exe\n",
    "        driver = webdriver.Chrome(service=service, options=chrome_options)\n",
    "        driver.get('https://accounts.firefox.com')\n",
    "\n",
    "        element = WebDriverWait(driver, 120).until(\n",
    "        EC.presence_of_element_located((By.NAME, 'email')))\n",
    "\n",
    "        email_input = driver.find_element(By.NAME, 'email')\n",
    "        email_input.send_keys(email)\n",
    "        email_input.send_keys(Keys.RETURN)\n",
    "        \n",
    "        WebDriverWait(driver, 120).until(\n",
    "            lambda driver: 'signin?' in driver.execute_script(\"return window.location.href;\") or \n",
    "                        'signup?' in driver.execute_script(\"return window.location.href;\")\n",
    "        )\n",
    "        current_url=driver.execute_script(\"return window.location.href;\")\n",
    "\n",
    "        driver.quit()\n",
    "\n",
    "        if 'signin' in current_url:\n",
    "            return True\n",
    "        else:\n",
    "            return False\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"An error occurred: {e}\")\n",
    "        return None\n",
    "\n",
    "\n",
    "print(checker('...', '...')) #email, proxy - login:password@host:port\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "import time\n",
    "from typing import Optional\n",
    "import zipfile\n",
    "\n",
    "proxy='QISr2hwBRVj7:RNW78Fm5@pool.proxy.market:10323'\n",
    "email='jim-3000@mail.ru'\n",
    "username, password_host_port = proxy.split(':', 1)\n",
    "password, host_port = password_host_port.split('@', 1)\n",
    "host, port = host_port.split(':')\n",
    "\n",
    "manifest_json = \"\"\"\n",
    "{\n",
    "    \"version\": \"1.0.0\",\n",
    "    \"manifest_version\": 2,\n",
    "    \"name\": \"Chrome Proxy\",\n",
    "    \"permissions\": [\n",
    "        \"proxy\",\n",
    "        \"tabs\",\n",
    "        \"unlimitedStorage\",\n",
    "        \"storage\",\n",
    "        \"<all_urls>\",\n",
    "        \"webRequest\",\n",
    "        \"webRequestBlocking\"\n",
    "    ],\n",
    "    \"background\": {\n",
    "        \"scripts\": [\"background.js\"]\n",
    "    },\n",
    "    \"minimum_chrome_version\":\"22.0.0\"\n",
    "}\n",
    "\"\"\"\n",
    "\n",
    "background_js = \"\"\"\n",
    "var config = {\n",
    "        mode: \"fixed_servers\",\n",
    "        rules: {\n",
    "        singleProxy: {\n",
    "            scheme: \"http\",\n",
    "            host: \"%s\",\n",
    "            port: parseInt(%s)\n",
    "        },\n",
    "        bypassList: [\"localhost\"]\n",
    "        }\n",
    "    };\n",
    "\n",
    "chrome.proxy.settings.set({value: config, scope: \"regular\"}, function() {});\n",
    "\n",
    "function callbackFn(details) {\n",
    "    return {\n",
    "        authCredentials: {\n",
    "            username: \"%s\",\n",
    "            password: \"%s\"\n",
    "        }\n",
    "    };\n",
    "}\n",
    "\n",
    "chrome.webRequest.onAuthRequired.addListener(\n",
    "            callbackFn,\n",
    "            {urls: [\"<all_urls>\"]},\n",
    "            ['blocking']\n",
    ");\n",
    "\"\"\" % ((host, port, username, password))\n",
    "\n",
    "\n",
    "\n",
    "try:\n",
    "    # Создание экземпляра веб-драйвера с заданными опциями\n",
    "    chrome_options = webdriver.ChromeOptions()\n",
    "\n",
    "    pluginfile = 'proxy_auth_plugin.zip'\n",
    "\n",
    "    with zipfile.ZipFile(pluginfile, 'w') as zp:\n",
    "        zp.writestr(\"manifest.json\", manifest_json)\n",
    "        zp.writestr(\"background.js\", background_js)\n",
    "\n",
    "    chrome_options.add_extension(pluginfile)\n",
    "\n",
    "    service = Service('C:\\\\Users\\\\User\\\\Desktop\\\\chrome_driver\\\\chromedriver.exe')\n",
    "    driver = webdriver.Chrome(service=service, options=chrome_options)\n",
    "    driver.get('https://accounts.firefox.com/')\n",
    "\n",
    "    element = WebDriverWait(driver, 120).until(\n",
    "    EC.presence_of_element_located((By.NAME, 'email')))\n",
    "\n",
    "    email_input = driver.find_element(By.NAME, 'email')\n",
    "    email_input.send_keys(email)\n",
    "    email_input.send_keys(Keys.RETURN)\n",
    "\n",
    "    WebDriverWait(driver, 120).until(\n",
    "        lambda driver: 'signin?' in driver.execute_script(\"return window.location.href;\") or \n",
    "                       'signup?' in driver.execute_script(\"return window.location.href;\")\n",
    "    )\n",
    "    current_url=driver.execute_script(\"return window.location.href;\")\n",
    "\n",
    "    driver.quit()\n",
    "    if 'signin' in current_url:\n",
    "            print(True)\n",
    "    else:\n",
    "            print(False)\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"An error occurred: {e}\")\n",
    "    print(None)\n",
    "\n",
    "\n",
    "# print(checker('jim-3000@mail.ru', 'QISr2hwBRVj7:RNW78Fm5@pool.proxy.market:10323'))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'https://accounts.firefox.com/signup?showReactApp=true&deviceId=603f505316b643c19b2ceb1b7d0c763d&flowBeginTime=1737651049009&flowId=9d575a16a33c11a4a9df8c8da91c4ed375973455af310773eeaaff29e51b58ec&email=fdsgsegwrstgdsf%40mail.ru&emailStatusChecked=true'"
      ]
     },
     "execution_count": 93,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "driver.execute_script(\"return window.location.href;\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
